### ISSUE TITLE
Add an option to disable styling of inactive tabs

### ISSUE THREAD

**Issue by qtlis** [JustOff/lull-the-tabs#9]
It is redundant when using Tab Mix Plus, since TMP provides similar, but more customisable functionality.

**Comment by JustOff** [comment]
There are reasons for which I consider it undesirable to customize inactive tab styles on the fly. However, you can always override opacity using [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css):

```css
@-moz-document url("chrome://browser/content/browser.xul") {
  .tabbrowser-tab[pending=true],
  menuitem.alltabs-item[pending=true] {
    opacity: 1 !important;
  }
}
```
